import { Animal } from './animal-rescue-service';

export const ANIMALS_DATA: Animal[] = [
  {
    id: 'dog-001',
    name: 'Max',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 3,
    gender: 'male',
    size: 'large',
    color: 'Golden',
    description: 'Friendly and energetic dog, loves playing fetch and swimming.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    energyLevel: 'high',
    adoptionFee: 250,
    dateArrived: '2024-01-15',
    adopted: false
  },
  {
    id: 'cat-001',
    name: 'Luna',
    species: 'cat',
    breed: 'Domestic Shorthair',
    age: 2,
    gender: 'female',
    size: 'medium',
    color: 'Black and white',
    description: 'Sweet and gentle cat who loves to cuddle and purr.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: false,
    energyLevel: 'low',
    adoptionFee: 125,
    dateArrived: '2024-02-03',
    adopted: false
  },
  {
    id: 'dog-002',
    name: 'Bella',
    species: 'dog',
    breed: 'Labrador Mix',
    age: 5,
    gender: 'female',
    size: 'medium',
    color: 'Chocolate brown',
    description: 'Calm and well-trained dog, perfect for families.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    energyLevel: 'medium',
    adoptionFee: 200,
    dateArrived: '2024-01-28',
    adopted: false
  },
  {
    id: 'cat-002',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Siamese',
    age: 4,
    gender: 'male',
    size: 'medium',
    color: 'Cream and brown',
    description: 'Talkative and intelligent cat who enjoys interactive toys.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: false,
    goodWithPets: false,
    energyLevel: 'medium',
    adoptionFee: 150,
    dateArrived: '2024-02-10',
    adopted: false
  },
  {
    id: 'dog-003',
    name: 'Charlie',
    species: 'dog',
    breed: 'Beagle',
    age: 1,
    gender: 'male',
    size: 'small',
    color: 'Tri-color',
    description: 'Young and playful puppy, needs training and socialization.',
    vaccinated: true,
    spayedNeutered: false,
    goodWithKids: true,
    goodWithPets: true,
    energyLevel: 'high',
    adoptionFee: 300,
    dateArrived: '2024-02-20',
    adopted: false
  },
  {
    id: 'cat-003',
    name: 'Mittens',
    species: 'cat',
    breed: 'Maine Coon',
    age: 6,
    gender: 'female',
    size: 'large',
    color: 'Gray tabby',
    description: 'Gentle giant who loves being brushed and enjoys quiet companionship.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: true,
    energyLevel: 'low',
    adoptionFee: 175,
    dateArrived: '2024-01-05',
    adopted: false
  },
  {
    id: 'rabbit-001',
    name: 'Cocoa',
    species: 'rabbit',
    breed: 'Holland Lop',
    age: 2,
    gender: 'female',
    size: 'small',
    color: 'Brown',
    description: 'Adorable lop-eared rabbit who loves hay and fresh vegetables.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: true,
    goodWithPets: false,
    energyLevel: 'medium',
    adoptionFee: 75,
    dateArrived: '2024-02-12',
    adopted: false
  },
  {
    id: 'dog-004',
    name: 'Rocky',
    species: 'dog',
    breed: 'German Shepherd',
    age: 7,
    gender: 'male',
    size: 'large',
    color: 'Black and tan',
    description: 'Senior dog with a calm temperament, excellent guard dog.',
    vaccinated: true,
    spayedNeutered: true,
    goodWithKids: false,
    goodWithPets: false,
    energyLevel: 'low',
    adoptionFee: 150,
    dateArrived: '2024-01-20',
    adopted: false
  }
];
