"""Animal data for the rescue service."""

from typing import List

from .animal_rescue_service import Animal

ANIMALS_DATA: List[Animal] = [
    {
        "id": "dog-001",
        "name": "Max",
        "species": "dog",
        "breed": "Golden Retriever",
        "age": 3,
        "gender": "male",
        "size": "large",
        "color": "Golden",
        "description": "Friendly and energetic dog, loves playing fetch and swimming.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": True,
        "good_with_pets": True,
        "energy_level": "high",
        "adoption_fee": 250,
        "date_arrived": "2024-01-15",
        "adopted": False,
    },
    {
        "id": "cat-001",
        "name": "Luna",
        "species": "cat",
        "breed": "Domestic Shorthair",
        "age": 2,
        "gender": "female",
        "size": "medium",
        "color": "Black and white",
        "description": "Sweet and gentle cat who loves to cuddle and purr.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": True,
        "good_with_pets": False,
        "energy_level": "low",
        "adoption_fee": 125,
        "date_arrived": "2024-02-03",
        "adopted": False,
    },
    {
        "id": "dog-002",
        "name": "Bella",
        "species": "dog",
        "breed": "Labrador Mix",
        "age": 5,
        "gender": "female",
        "size": "medium",
        "color": "Chocolate brown",
        "description": "Calm and well-trained dog, perfect for families.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": True,
        "good_with_pets": True,
        "energy_level": "medium",
        "adoption_fee": 200,
        "date_arrived": "2024-01-28",
        "adopted": False,
    },
    {
        "id": "cat-002",
        "name": "Whiskers",
        "species": "cat",
        "breed": "Siamese",
        "age": 4,
        "gender": "male",
        "size": "medium",
        "color": "Cream and brown",
        "description": "Talkative and intelligent cat who enjoys interactive toys.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": False,
        "good_with_pets": False,
        "energy_level": "medium",
        "adoption_fee": 150,
        "date_arrived": "2024-02-10",
        "adopted": False,
    },
    {
        "id": "dog-003",
        "name": "Charlie",
        "species": "dog",
        "breed": "Beagle",
        "age": 1,
        "gender": "male",
        "size": "small",
        "color": "Tri-color",
        "description": "Young and playful puppy, needs training and socialization.",
        "vaccinated": True,
        "spayed_neutered": False,
        "good_with_kids": True,
        "good_with_pets": True,
        "energy_level": "high",
        "adoption_fee": 300,
        "date_arrived": "2024-02-20",
        "adopted": False,
    },
    {
        "id": "cat-003",
        "name": "Mittens",
        "species": "cat",
        "breed": "Maine Coon",
        "age": 6,
        "gender": "female",
        "size": "large",
        "color": "Gray tabby",
        "description": "Gentle giant who loves being brushed and enjoys quiet companionship.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": True,
        "good_with_pets": True,
        "energy_level": "low",
        "adoption_fee": 175,
        "date_arrived": "2024-01-05",
        "adopted": False,
    },
    {
        "id": "rabbit-001",
        "name": "Cocoa",
        "species": "rabbit",
        "breed": "Holland Lop",
        "age": 2,
        "gender": "female",
        "size": "small",
        "color": "Brown",
        "description": "Adorable lop-eared rabbit who loves hay and fresh vegetables.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": True,
        "good_with_pets": False,
        "energy_level": "medium",
        "adoption_fee": 75,
        "date_arrived": "2024-02-12",
        "adopted": False,
    },
    {
        "id": "dog-004",
        "name": "Rocky",
        "species": "dog",
        "breed": "German Shepherd",
        "age": 7,
        "gender": "male",
        "size": "large",
        "color": "Black and tan",
        "description": "Senior dog with a calm temperament, excellent guard dog.",
        "vaccinated": True,
        "spayed_neutered": True,
        "good_with_kids": False,
        "good_with_pets": False,
        "energy_level": "low",
        "adoption_fee": 150,
        "date_arrived": "2024-01-20",
        "adopted": False,
    },
]
